spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  liquibase:
    user: sa
    password:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    change-log: classpath:db/master.xml

logging:
  level:
    com.meawallet.usercrud: DEBUG
#    root: TRACE